CREATE TABLE IF NOT EXISTS __SESSION_MEMORY_TABLE__ (
  session_id TEXT PRIMARY KEY,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  messages JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE INDEX IF NOT EXISTS __SESSION_MEMORY_TABLE___updated_at_idx
  ON __SESSION_MEMORY_TABLE__ (updated_at DESC);
